// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh_t7LG4ES-LxoYEEkSyyWSQJUPYlahwk',
    appId: '1:356246990133:web:83e894946fa44f8682307c',
    messagingSenderId: '356246990133',
    projectId: 'mini-project-6079d',
    authDomain: 'mini-project-6079d.firebaseapp.com',
    storageBucket: 'mini-project-6079d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVuKySJ6_tTetqqHRGctYTHObh6ng3Ins',
    appId: '1:356246990133:android:4692b7d2d05fb8ea82307c',
    messagingSenderId: '356246990133',
    projectId: 'mini-project-6079d',
    storageBucket: 'mini-project-6079d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7WiHcY0p5FRrd1NRq1FGTFrNGX08iu2o',
    appId: '1:356246990133:ios:e5ccf5a3df29a09582307c',
    messagingSenderId: '356246990133',
    projectId: 'mini-project-6079d',
    storageBucket: 'mini-project-6079d.appspot.com',
    iosBundleId: 'com.example.miniProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7WiHcY0p5FRrd1NRq1FGTFrNGX08iu2o',
    appId: '1:356246990133:ios:e5ccf5a3df29a09582307c',
    messagingSenderId: '356246990133',
    projectId: 'mini-project-6079d',
    storageBucket: 'mini-project-6079d.appspot.com',
    iosBundleId: 'com.example.miniProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh_t7LG4ES-LxoYEEkSyyWSQJUPYlahwk',
    appId: '1:356246990133:web:05d7a7e83167f76e82307c',
    messagingSenderId: '356246990133',
    projectId: 'mini-project-6079d',
    authDomain: 'mini-project-6079d.firebaseapp.com',
    storageBucket: 'mini-project-6079d.appspot.com',
  );
}
